### ISSUE TITLE
Display additional relevant information in the result

### ISSUE THREAD

**Issue by ernilambar** [WordPress/plugin-check-action#120]
Output on the check does not show in information related to file, lice number, etc. But in the screenshot provided in the README is different. Is there any parameter to customize the result? Am I missing something?

<img width="907" alt="Screenshot 2024-07-06 at 2 02 09 PM" src="https://github.com/WordPress/plugin-check-action/assets/2098823/ee0418eb-6285-42ab-a9b3-8a73a061cf8f">

**Comment by swissspidy** [comment]
Messages are added inline as annotations in each file on the affected line

**Comment by ernilambar** [comment]
Ah. Found it. 
<img width="909" alt="Screenshot 2024-07-06 at 8 49 15 PM" src="https://github.com/WordPress/plugin-check-action/assets/2098823/1fc3953d-3d0a-44f6-a5da-21951ea44a41">
