### ISSUE TITLE
Error: Your plugin has no license declared in Plugin Header

### ISSUE THREAD

**Issue by jcvignoli** [WordPress/plugin-check-action#138]
Hello,
The workflow fails to run with the following message:
`Error: Your plugin has no license declared in Plugin Header. Please update your plugin header with a GPLv2 (or later) compatible license.`

My readme licence tags:
```
License: GPLv3
License URI: https://www.gnu.org/licenses/gpl-3.0.en.html
```
Thanks in advance for checking it!

**Comment by jcvignoli** [comment]
This is my plugin: https://wordpress.org/plugins/lumiere-movies/
Yes, I get the same error on a local dev site.

**Comment by swissspidy** [comment]
In that case, this would be an issue with the Plugin Check plugin, not with this GitHub Action. Issues with the plugins hould be reported at https://github.com/WordPress/plugin-check/.

That said, Plugin Check does not look at PHPdoc block like yours. It needs to be a **proper plugin header**. Example:

https://github.com/WordPress/performance/blob/b319595c3c1ca567bcca122dca561bc714d772e4/plugins/performance-lab/load.php#L11-L13

See https://developer.wordpress.org/plugins/plugin-basics/header-requirements/ for more detailed information about plugin headers.
