### ISSUE TITLE
It does not show lines and files in the output

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/plugin-check-action#162]
I'm using and in the output you cannot know where is the problem. It does not give you the detail for filename and line.

**Comment by davidperezgar** [comment]
Ahm, ok it's not in the execution log
![Captura de pantalla 2024-09-11 a las 23 25 23](https://github.com/user-attachments/assets/4172c097-7811-412f-9aed-007f57300abc)
But I can see in annotations...
![annotations](https://github.com/user-attachments/assets/a4e50178-cda1-4a95-9ef6-2fb8ab997abd)

**Comment by swissspidy** [comment]
Yes, all messages are added as annotations so you don‘t actually have to go through the log :-)

So I‘d say that this is working as intended

**Comment by davidperezgar** [comment]
Ok I agree then.
