### ISSUE TITLE
boils down to PHPCS

### ISSUE THREAD

**Issue by szepeviktor** [WordPress/plugin-check-action#89]
@swissspidy Could it be that

- this action runs a plugin
- that plugin run PHPCS
- So I just need a ruleset??

**Comment by swissspidy** [comment]
Hehe almost! :)

There are two types of checks:

* Static checks
	* Contains both PHPCS checks and other types of manual checks (e.g. for checking the readme)
* Runtime checks
	* Actually activates the plugin and does some more tests

Plugin developers are of course encouraged to use PHPCS/WPCS in their development workflow, as usual. Plugin Check is then a small addition to that.

Hope that explains it.

FWIW the current setup isn't ideal, for example the core functionality should be extracted into a WP-CLI command or so (see https://github.com/WordPress/plugin-check/issues/153). And there are still many more runtime checks that have yet to be added. I recommend filing any suggestions on the main Plugin Check repo.

**Comment by swissspidy** [comment]
> and other types of manual checks

* [Detect and warn about existence of hidden files or application files in the plugin folder](https://github.com/WordPress/plugin-check/blob/e6cdfac9977b6a7da830012031816abac5512c86/includes/Checker/Checks/File_Type_Check.php)
* [Prevent the use of `localhost` or `127.0.0.1` in the code](https://github.com/WordPress/plugin-check/blob/e6cdfac9977b6a7da830012031816abac5512c86/includes/Checker/Checks/Localhost_Check.php)
* [Disallow usage of the `Update URI` header or similar to download stuff from other places](https://github.com/WordPress/plugin-check/blob/e6cdfac9977b6a7da830012031816abac5512c86/includes/Checker/Checks/Plugin_Updater_Check.php)
* [Disallow usage of reserved words and trademarks](https://github.com/WordPress/plugin-check/blob/e6cdfac9977b6a7da830012031816abac5512c86/includes/Checker/Checks/Trademarks_Check.php)
* [Disallow obfuscated code](https://github.com/WordPress/plugin-check/blob/e6cdfac9977b6a7da830012031816abac5512c86/includes/Checker/Checks/Code_Obfuscation_Check.php)

> and does some more tests

* [Detect if a stylesheet is enqueued on all pages, which is usually a mistake](https://github.com/WordPress/plugin-check/blob/e6cdfac9977b6a7da830012031816abac5512c86/includes/Checker/Checks/Enqueued_Styles_Scope_Check.php)
* [Detect whether the combined size of all JS on a page exceeds a certain threshold](https://github.com/WordPress/plugin-check/blob/e6cdfac9977b6a7da830012031816abac5512c86/includes/Checker/Checks/Enqueued_Scripts_Size_Check.php)
* More performance-related checks are in discussion (https://github.com/WordPress/plugin-check/issues/443)

**Comment by szepeviktor** [comment]
Thank you.
